######################################################################
#
# File name : stream_switch_250mhz_compile.do
# Created on: Fri Dec 17 06:05:53 UTC 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../../../plugin/stream-switch/box_250mhz" "+incdir+../../../../../../../plugin/p2p/box_322mhz" "+incdir+../../../../open_nic_shell.ip_user_files/ipstatic/hdl" "+incdir+../../../../../../../src" "+incdir+../../../../../../../plugin/stream-switch" \
"../../../../../vivado_ip/axi_stream_pipeline/sim/axi_stream_pipeline.v" \
"../../../../../vivado_ip/axi_lite_clock_converter/sim/axi_lite_clock_converter.v" \
"../../../../open_nic_shell.gen/sources_1/ip/axis_switch_combiner_tdest/sim/axis_switch_combiner_tdest.v" \
"../../../../open_nic_shell.gen/sources_1/ip/axis_switch_splitter_axilite/sim/axis_switch_splitter_axilite.v" \
"../../../../open_nic_shell.gen/sources_1/ip/stream_switch_axi_crossbar/sim/stream_switch_axi_crossbar.v" \
"../../../../../../../plugin/stream-switch/stream_switch_address_map.v" \

vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../../../../plugin/stream-switch/box_250mhz" "+incdir+../../../../../../../plugin/p2p/box_322mhz" "+incdir+../../../../open_nic_shell.ip_user_files/ipstatic/hdl" "+incdir+../../../../../../../src" "+incdir+../../../../../../../plugin/stream-switch" \
"../../../../../../../src/utility/axi_lite_register.sv" \
"../../../../../../../src/utility/axi_lite_slave.sv" \
"../../../../../../../src/utility/axi_stream_size_counter.sv" \
"../../../../../../../plugin/stream-switch/byte_counter_250mhz.sv" \
"../../../../../../../src/utility/generic_reset.sv" \
"../../../../../../../plugin/stream-switch/stream_switch_250mhz.sv" \

vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../../../../plugin/stream-switch/box_250mhz" "+incdir+../../../../../../../plugin/p2p/box_322mhz" "+incdir+../../../../open_nic_shell.ip_user_files/ipstatic/hdl" "+incdir+../../../../../../../src" "+incdir+../../../../../../../plugin/stream-switch" \
"../../../../../../../src/utility/generic_reset.sv" \
"../../../../../../../src/box_250mhz/box_250mhz.sv" \
"../../../../open_nic_shell.gen/sources_1/ip/box_250mhz_axi_crossbar/synth/box_250mhz_axi_crossbar.v" \
"../../../../../../../plugin/stream-switch/box_250mhz/box_250mhz_address_map.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

